project_identifier_env: CROWDIN_PROJECT_ID
api_key_env: CROWDIN_API_KEY
base_path: src
files:
  - source: /translations/messages.json
    translation: /translations/messages.%two_letters_code%.%file_extension%