version: 2

defaults: &defaults
  working_directory: ~/formatting
  docker:
    - image: circleci/node:10.6-browsers

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run release-to-github
      - run:
          name: Publish on npm
          command: npm publish --access=public

workflows:
  version: 2
  build-test-and-release:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - build
      - release:
          context: frontend-publish
          requires:
            - test
          filters:
            branches:
              only: master
