version: 2

defaults: &defaults
  working_directory: ~/formatting
  docker:
    - image: circleci/node:lts-browsers

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  push-and-pull-translations:
    working_directory: ~/formatting
    docker:
      - image: circleci/java:latest
    steps:
      - attach_workspace:
          at: ~/formatting
      - run:
          name: Download CrowdIn CLI
          command: |
            wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
            sudo dpkg -i crowdin.deb
      - run:
          name: Push translations
          command: crowdin push -b ${CIRCLE_BRANCH}
      - run:
          name: Pull translations
          command: crowdin pull -b ${CIRCLE_BRANCH}
      - run:
          name: List files
          command: ls -l src/translations
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run release-to-github
      - run:
          name: Publish on npm
          command: npm publish --access=public

workflows:
  version: 2
  build-test-and-release:
    jobs:
      - dependencies
      - push-and-pull-translations:
          requires:
            - dependencies
      - build:
          requires:
            - push-and-pull-translations
      - test:
          requires:
            - build
      - release:
          context: frontend-publish
          requires:
            - test
          filters:
            branches:
              only: master
