version: 2

defaults: &defaults
  working_directory: ~/formatting
  docker:
    - image: circleci/node:10.6-browsers

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/formatting
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - dependencies
      - test
