export const DEFAULT_LOCALE = 'en-GB';
export const MIN_PRECISION = 0;
export const MAX_PRECISION = 20;
export const NUMBER_OF_EXCHANGE_RATE_SIGNIFICANT_DIGITS = 6;
export const EXCHANGE_RATE_INVERSION_THRESHOLD = 0.3;
